<<: &shared
  language_name: Mohawk
mappings:
  - display_name: Mohawk to IPA
    mapping: moh_to_ipa.json
    in_lang: moh-equiv
    out_lang: moh-ipa
    case_sensitive: false
    norm_form: NFC
    rule_ordering: as-written
    abbreviations: abbreviations.csv
    authors:
      - Aidan Pine
      - Akwiratékha' Martin
    <<: *shared
  - display_name: IPA to Mohawk
    mapping: moh_to_ipa.json
    in_lang: moh-ipa
    reverse: true
    out_lang: moh
    case_sensitive: false
    norm_form: NFC
    rule_ordering: as-written
    abbreviations: abbreviations.csv
    authors:
      - Aidan Pine
      - Akwiratékha' Martin
    <<: *shared
  - display_name: Mohawk Equivalencies
    mapping: moh_equiv.json
    in_lang: moh
    out_lang: moh-equiv
    case_sensitive: false
    norm_form: NFC
    rule_ordering: as-written
    abbreviations: abbreviations.csv
    authors:
      - Aidan Pine
    <<: *shared
